### ISSUE TITLE
Resource Warning during Unittest

### ISSUE THREAD

**Issue by TheTesla** [inwx/python-client#11]
```
/usr/lib/python3.8/socket.py:740: ResourceWarning: unclosed <socket.socket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('192.168.1.103', 60754), raddr=('185.181.104.71', 443)>
  self._sock = None
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```
This happens during nameserver.createRecord, nameserver.deleteRecord, nameserver.updateRecord and nameserver.info if called by python3 unittest.

**Comment by inwx-developer** [comment]
We have made many attempts to reproduce the warning but have not been able to, therefore the issue is closed.
If the problem persists on your end, please open a new bug report with more detailed information.
